from typing import Any

version: str

def attach_to_tracee_and_begin(*args, **kwargs) -> Any: ...
def did_segfault(*args, **kwargs) -> Any: ...
def get_registers_from_tracee(*args, **kwargs) -> Any: ...
def read_from_tracee(*args, **kwargs) -> Any: ...
def run_until_enter_or_exit_of_next_syscall(*args, **kwargs) -> Any: ...
def set_registers_in_tracee(*args, **kwargs) -> Any: ...
def write_to_tracee(*args, **kwargs) -> Any: ...
